$("body")[0].innerHTML='<audio id="music" src="music/PilgrimsOnALongJourney.mp3" loop="loop"></audio><audio id="diesound" src="music/glass.wav"></audio><audio id="killsound" src="music/kill.wav"></audio><audio id="diamondsound" src="music/diamond.wav"></audio>';timer&&window.clearInterval(timer);var width=document.documentElement.clientWidth,height=document.documentElement.clientHeight;
$("body").prepend('<canvas id="canv" tabindex="0" style="position:absolute;left:0px;top:0px;" width='+width+"px height="+height+"px>\u8bf7\u6362\u4e2a\u6d4f\u89c8\u5668\u3002\u3002</canvas>");var cv=$("#canv")[0].getContext("2d"),cos=Math.cos,sin=Math.sin,random=Math.random,PI=Math.PI,abs=Math.abs,atan2=Math.atan2,round=Math.round,floor=Math.floor,sqrt=Math.sqrt;function cube(a){return a*a}function rad(a){return a/180*PI}function xy(a){return{x:a.r*cos(a.t),y:a.r*sin(a.t)}}
function dis2(a,b,c,d){return(a-c)*(a-c)+(b-d)*(b-d)}function ran(a,b){return a+(b-a)*random()}function ranInt(a,b){return floor(a+(b-a+1)*random())}function min(a,b){return a>b?b:a}
var _gamename="ENDLESS SEA",_instructions="TUTORIAL",_about="ABOUT",_startgame="START GAME",_pause="PAUSE",_continue="CONTINUE",_gameover="DREAM AWAKE",_scoreis="YOUR SCORE: ",_ranking="RANKING",_tryagain="TRY AGAIN",_top_score="Score: ",_top_life="Life: ",_top_level="Level: ",_life="Life: ",_wudi="Superfish",_jiansu="Speed Down",_qingping="Big Bomb",_1up="1 UP",_bianxiao="Small World",mx,my,bg,pl,plSize,cursorSize,ballSize,bigBallSize,bSize,butterflySize,starSize,d1,d2,d3,t1,t2,score,u1,u2,fps,planeShape,
butterflyLine,butterflyShape,diamondShape,Star_6,balls,bigBalls,butterflys,stars,diamonds,waves,ballSpeed,bigBallSpeed,butterflySpeed,starSpeed,waveSpeed,waveRSpeed,waveWidth,waveMaxR,waveR,ballDensity,bigBallDensity,butterflyDensity,diamondDensity,ballStyle,instructionsContent,aboutContent,clock,died,level,judge,startBgColor=ranInt(0,359),bgColorTimer=0,life,wudi,wudiTimer,smallTimer,slowTimer,info,timer,flash,pause,pauseTimes,playNum,scoreArr;playNum=0;scoreArr=[];
function prepossessing(){mx=width/7;my=height/2;pl={x:width/9,y:height/2,vx:0,vy:0,ax:0,ay:0,arc:0};plSize=20;cursorSize=6;ballSize=4;bigBallSize=40;bSize=10;butterflySize=bSize-2;starSize=6;d1=25;d2=d1/25*30;d3=d1/25*27;t1=20;t2=40;u1=6;u2=80;fps=60;ballStyle="#eef";planeShape=[{r:1*plSize,t:PI+3.14},{r:.716*plSize,t:PI+-2.98},{r:.443*plSize,t:PI+-2.49},{r:.443*plSize,t:PI-.65},{r:.716*plSize,t:PI-.25},{r:1*plSize,t:PI+0},{r:1*plSize,t:PI+0},{r:.716*plSize,t:PI+.25},{r:.443*plSize,t:PI+.65},{r:.443*
plSize,t:PI+2.49},{r:.716*plSize,t:PI+2.98}];butterflyLine=[{r:3,t:rad(15)},{r:3,t:rad(345)}];butterflyShape=[{r:1,t:0},{r:2.7,t:rad(35)},{r:3.5,t:rad(45)},{r:3.2,t:rad(55)},{r:2.33,t:rad(95)},{r:1,t:rad(90)},{r:2,t:rad(120)},{r:2.1,t:rad(150)},{r:1,t:rad(180)},{r:2.1,t:rad(210)},{r:2,t:rad(240)},{r:1,t:rad(270)},{r:2.33,t:rad(265)},{r:3.2,t:rad(305)},{r:3.5,t:rad(315)},{r:2.7,t:rad(325)}];diamondShape=[{r:d1,t:PI+rad(90+t1+t2/2)},{r:d2,t:PI+rad(90+t2/2)},{r:d2,t:PI+rad(90-t2/2)},{r:d1,t:PI+rad(90-
t1-t2/2)},{r:0,t:PI}];Star_6=[{r:starSize,t:rad(90)},{r:starSize/2*1.5,t:rad(60)},{r:starSize,t:rad(30)},{r:starSize/2*1.5,t:rad(0)},{r:starSize,t:rad(-30)},{r:starSize/2*1.5,t:rad(-60)},{r:starSize,t:rad(-90)},{r:starSize/2*1.5,t:rad(-120)},{r:starSize,t:rad(-150)},{r:starSize/2*1.5,t:rad(-180)},{r:starSize,t:rad(-210)},{r:starSize/2*1.5,t:rad(-240)}];for(var a in butterflyShape)butterflyShape[a].r*=bSize;balls=[];bigBalls=[];butterflys=[];stars=[];diamonds=[];waves=[];ballSpeed=4.2;bigBallSpeed=
3.8;butterflySpeed=.35;starSpeed=6;waveSpeed=ballSpeed;waveNum=8;waveR=5;waveRSpeed=.7;waveWidth=6;waveMaxR=100;ballDensity=.5;bigBallDensity=.08;butterflyDensity=5;starDensity=8;diamondDensity=.0012;judge={ball:cube(plSize/4+ballSize),bigBall:cube(plSize/4+bigBallSize),butterfly:cube(plSize/4+butterflySize),star:cube(plSize/4+starSize),diamond:cube(plSize/4+20)};score=clock=0;died=!1;level=0;life=5;wudi=!1;window.clearTimeout(wudiTimer);window.clearTimeout(smallTimer);window.clearTimeout(slowTimer);
flash=0;instructionsContent='<b style="font-size:22px;"><p>INSTRUCTION</p></b><p>Move mouse to control the fish</p><p>Diamonds can help you gain special abilities</p><p>Press Space or Enter for pause(^^)</p>';aboutContent='<b style="font-size:22px;"><p>ABOUT US</p></b><p>\u5468\u4f2f\u5a01 zhou_bw@yeah.net</p><p>\u6797\u6768\u6e44 linym012@163.com</p><p>Thanks for playing(*\u00b4\u25bd\uff40*)</p>';info="";pause=!1;pauseTimes=30;playNum=0;scoreArr=[]}prepossessing();drawBG();
$("body").append('<div class="title">'+_gamename+'</div><div id="startgame"><div id="instructions">'+_instructions+'</div><div id="about">'+_about+'</div><div id="startbutton" class="button">'+_startgame+"</div></div>");$("body").append('<div class="moreinfo" id="left"></div>');$("body").append('<div class="moreinfo" id="right"></div>');$("body").append('<div class="moreinfo" id="right2"></div>');$("#startgame").css("left",width/2-200+"px");$("#startgame").css("top",height/2-100+"px");
$("#left").css("left","20px");$("#left").css("width",width/2-240+"px");$("#left").css("top",height/2-100+"px");$("#right").css("left",width/2+220+"px");$("#right").css("width",width/2-240+"px");$("#right").css("top",height/2-100+"px");$("#right2").css("left",width/2+220+"px");$("#right2").css("width",width/2-240+"px");$("#right2").css("top",height/2-100+"px");$("#right2").css("padding-top","0px");$(".title").css("top",height/2-200+"px");$(".title").css("left",width/2-$(".title").width()/2+"px");addHelpInfo();
addAboutInfo();addRankingInfo();function hsvToRgb(a,b,c){var d=floor(a/60),f=a/60-d;a=floor(255*c);var e=floor(255*c*(1-b)),g=floor(255*c*(1-f*b));b=floor(255*c*(1-(1-f)*b));return[{r:a,g:b,b:e},{r:g,g:a,b:e},{r:e,g:a,b:b},{r:e,g:g,b:a},{r:b,g:e,b:a},{r:a,g:e,b:g}][d]}
function drawBG(){if(0==bgColorTimer%10){var a=hsvToRgb((startBgColor+bgColorTimer/10)%360,.14,.92),b=hsvToRgb((startBgColor+bgColorTimer/10)%360,.57,.77);bg=cv.createLinearGradient(0,0,0,height);bg.addColorStop(0,"rgb("+a.r+","+a.g+","+a.b+")");bg.addColorStop(1,"rgb("+b.r+","+b.g+","+b.b+")")}cv.save();cv.fillStyle=bg;cv.fillRect(0,0,width,height);cv.restore()}
function drawItem(a,b,c,d){cv.beginPath();var f=a.length;cv.moveTo(b+a[0].r*cos(a[0].t+d),c+a[0].r*sin(a[0].t+d));for(var e=0;e<f-1;e++)cv.lineTo(b+a[e+1].r*cos(a[e+1].t+d),c+a[e+1].r*sin(a[e+1].t+d));cv.lineTo(b+a[0].r*cos(a[0].t+d),c+a[0].r*sin(a[0].t+d));cv.closePath()}
function drawCursor(){cv.save();cv.beginPath();cv.lineWidth=1;cv.strokeStyle="#000";cv.shadowOffsetX=2;cv.shadowOffsetY=2;cv.shadowBlur=2;cv.shadowColor="#888";var a=cursorSize;cv.moveTo(mx-a,my);cv.lineTo(mx+a,my);cv.moveTo(mx,my-a);cv.lineTo(mx,my+a);cv.stroke();cv.restore()}
function drawPlane(){cv.save();cv.fillStyle="#e44";wudi&&clock/4&1&&(cv.fillStyle="rgba(238,68,68,0.15)");drawItem(planeShape,pl.x,pl.y,pl.arc);cv.fill();var a=8*cos(rad(7*clock)),b=.05*cos(rad(7*clock)),a=[{r:1*plSize,t:PI+0},{r:(1.67-b)*plSize,t:PI+rad(10+a)},{r:(1.67+b)*plSize,t:PI+rad(-10+a)}];drawItem(a,pl.x,pl.y,pl.arc);cv.fill();cv.beginPath();cv.arc(pl.x+.5*plSize*cos(pl.arc),pl.y+.5*plSize*sin(pl.arc),.1*plSize,0,2*Math.PI,!0);cv.fillStyle="#000000";cv.closePath();cv.fill();wudi&&(cv.beginPath(),
a=cv.createRadialGradient(pl.x,pl.y,0,pl.x,pl.y,1.3*plSize),a.addColorStop(0,"rgba(255,255,238,0)"),a.addColorStop(.84,"rgba(255,255,238,0.1)"),a.addColorStop(1,"rgba(255,255,238,1)"),cv.fillStyle=a,cv.arc(pl.x,pl.y,1.3*plSize,0,2*PI,!0),cv.closePath(),cv.fill());cv.restore()}function drawOneBall(a,b,c){cv.save();cv.beginPath();cv.fillStyle=ballStyle;cv.arc(a,b,c,0,2*PI,!0);cv.closePath();cv.fill();cv.restore()}
function drawBalls(){for(var a in balls)drawOneBall(balls[a].pos.x,balls[a].pos.y,balls[a].size)}function drawBigBallLightCircle(a,b,c){cv.save();cv.beginPath();var d=cv.createRadialGradient(a,b,0,a,b,c);d.addColorStop(0,"rgba(255,255,255,1)");d.addColorStop(.8,"rgba(255,255,255,0.23)");d.addColorStop(1,"rgba(255,255,255,0)");cv.fillStyle=d;cv.arc(a,b,c,0,2*PI,!0);cv.closePath();cv.fill();cv.restore()}
function drawOneBigBall(a,b,c){cv.save();cv.beginPath();var d=cv.createRadialGradient(a,b,0,a,b,c);d.addColorStop(0,"rgba(238,238,255,0)");d.addColorStop(.84,"rgba(238,238,255,0.1)");d.addColorStop(1,"rgba(238,238,255,1)");cv.fillStyle=d;cv.arc(a,b,c,0,2*PI,!0);cv.closePath();cv.fill();cv.restore();drawBigBallLightCircle(a-.614*c,b-.2*c,.17*c);drawBigBallLightCircle(a-.57*c,b-.323*c,.17*c);drawBigBallLightCircle(a-.462*c,b-.43*c,.17*c);drawBigBallLightCircle(a-.2*c,b-.615*c,.17*c);drawBigBallLightCircle(a+
.461*c,b+.492*c,.17*c);drawBigBallLightCircle(a+.554*c,b+.415*c,.17*c)}function drawBigBalls(){for(var a in bigBalls)drawOneBigBall(bigBalls[a].pos.x,bigBalls[a].pos.y,bigBalls[a].size)}
function drawOneButterfly(a,b,c,d){cv.save();cv.strokeStyle="white";cv.lineWidth=.5;cv.beginPath();for(var f in butterflyLine)cv.moveTo(a,b),cv.lineTo(a+butterflyLine[f].r*bSize*cos(butterflyLine[f].t+c),b+butterflyLine[f].r*bSize*sin(butterflyLine[f].t+c));cv.closePath();cv.stroke();cv.lineWidth=1;cv.fillStyle=d;cv.strokeStyle="#fff";drawItem(butterflyShape,a,b,c);cv.stroke();cv.fill();cv.restore();c=ballStyle;ballStyle="rgba(119,119,221,0.2)";drawOneBall(a,b,bSize);ballStyle="rgba(238,238,255,0.8)";
drawOneBall(a,b,bSize-2);ballStyle=c}function drawButterflys(){for(var a in butterflys)drawOneButterfly(butterflys[a].x,butterflys[a].y,butterflys[a].deg,butterflys[a].color)}function drawOneStar(a,b,c){cv.save();cv.fillStyle="rgba(255,255,128,0.9)";cv.strokeStyle="rgba(250,250,255,0.9)";cv.lineWidth=5;drawItem(Star_6,a,b,c);cv.stroke();cv.fill();cv.restore()}function drawStars(){for(var a in stars)drawOneStar(stars[a].x,stars[a].y,stars[a].deg)}
function drawOneDiamond(a,b){cv.save();var c=.8+.2*sin(rad(7*clock)),d=floor(245+10*sin(rad(7*clock)));cv.fillStyle="rgba("+d+","+d+",255,"+c+")";cv.strokeStyle="rgba(72,233,236,"+c+")";cv.lineWidth=1;drawItem(diamondShape,a,b,0);cv.stroke();cv.fill();d=[{},{},{},{},{}];cv.beginPath();cv.strokeStyle="rgba(72,233,236,"+c+")";cv.lineWidth=.6;for(i=0;i<diamondShape.length;i++)d[i]=xy(diamondShape[i]);cv.moveTo(a+d[0].x,b+d[0].y);cv.lineTo(a+d[3].x,b+d[3].y);cv.moveTo(a+d[2].x,b+d[2].y);cv.lineTo(a+d[4].x,
b+d[4].y);cv.lineTo(a+d[1].x,b+d[1].y);cv.moveTo(a,b+d[1].y);cv.lineTo(a-d2*cos(t2/2)/2,b+d[0].y);cv.moveTo(a,b+d[1].y);cv.lineTo(a+d2*cos(t2/2)/2,b+d[0].y);cv.stroke();cv.restore()}function drawDiamonds(){for(var a in diamonds)drawOneDiamond(diamonds[a].x,diamonds[a].y)}
function drawOneWave(a,b,c,d){cv.save();cv.beginPath();d=cv.createRadialGradient(a,b,0,a,b,c);d.addColorStop(.5,"rgba(233,233,233,0)");d.addColorStop(1-waveWidth/c/2,"rgba(233,233,233,"+(waveMaxR-c)/waveMaxR*.4+")");d.addColorStop(1,"rgba(233,233,233,0)");cv.fillStyle=d;cv.arc(a,b,c,0,2*PI,!0);cv.closePath();cv.fill();cv.restore()}function drawWaves(){for(var a in waves)drawOneWave(waves[a].x,waves[a].y,waves[a].r,a)}
function addBall(a){a=void 0==a?PI:a;var b=sqrt(dis2(width/2,height/2,0,0)),c=ran(-b,b);a={size:ran(ballSize,1.3*ballSize),color:"#eef",speed:ballSpeed+ran(0,1),pos:{x:width/2+c*cos(a-PI/2)+b*cos(PI-a),y:height/2+c*sin(a-PI/2)-b*sin(PI-a)},degree:a};balls.push(a)}
function addBigBall(a){a=void 0==a?PI:a;var b=sqrt(dis2(width/2,height/2,0,0)),c=ran(-b,b);a={size:ran(bigBallSize,1.2*bigBallSize),color:"#eef",speed:bigBallSpeed+ran(0,1),pos:{x:width/2+c*cos(a-PI/2)+b*cos(PI-a),y:height/2+c*sin(a-PI/2)-b*sin(PI-a)},degree:a};bigBalls.push(a)}
function addButterfly(){for(var a=width/butterflyDensity,b=ran(0,a),c=1.2*height,d=0;d<butterflyDensity;d++){var f,e=[255,255,255];e[f=ranInt(0,2)]=244;e[(f+ranInt(1,2))%3]=ranInt(100,244);f="rgba("+e[0]+","+e[1]+","+e[2]+",0.4)";butterflys.push({x:b+c+d*a,y:c,cx:b+c+d*a,cy:0,r:c,color:f,rspeed:rad(butterflySpeed-.02*d),deg:rad(180-10*d),pos:rad(90-10*d)})}b=ran(0,a);for(d=0;d<butterflyDensity;d++)e=[255,255,255],e[f=ranInt(0,2)]=244,e[(f+ranInt(1,2))%3]=ranInt(100,244),f="rgba("+e[0]+","+e[1]+","+
e[2]+",0.4)",butterflys.push({x:b+c+d*a,y:height-c,cx:b+c+d*a,cy:height,r:c,color:f,rspeed:-rad(butterflySpeed-.02*d),deg:rad(180+10*d),pos:rad(270+10*d)})}function addStar(){var a=width+50,b=height/2+height*cos(5*rad(clock))*.45;stars.push({x:a,y:b,deg:ran(0,1),aim:atan2(pl.y-b,pl.x-a)+(clock%3-1)*rad(3),rspeed:ran(rad(-10),rad(10))})}function addDiamond(){var a=width/10,b=9*a,a=b-(cube(ran(a,b))-a*a)/(b*b-a*a)*(b-a);diamonds.push({x:a,y:-50,speed:ran(1.5,2),func:ranInt(0,5)})}
function addWave(){waves.push({x:pl.x,y:pl.y,r:waveR});waves.length>waveNum&&waves.splice(0,1)}function ballMove(){for(var a=balls.length-1;0<=a;a--)balls[a].pos.x+=balls[a].speed*cos(balls[a].degree),balls[a].pos.y+=balls[a].speed*sin(balls[a].degree),dis2(balls[a].pos.x,balls[a].pos.y,pl.x,pl.y)<judge.ball&&kill(),-50>balls[a].pos.x&&balls.splice(a,1)}
function bigBallMove(){for(var a=bigBalls.length-1;0<=a;a--)bigBalls[a].pos.x+=bigBalls[a].speed*cos(bigBalls[a].degree),bigBalls[a].pos.y+=bigBalls[a].speed*sin(bigBalls[a].degree),dis2(bigBalls[a].pos.x,bigBalls[a].pos.y,pl.x,pl.y)<judge.bigBall&&kill(),-50>bigBalls[a].pos.x&&bigBalls.splice(a,1)}
function butterflyMove(){for(var a=butterflys.length-1;0<=a;a--)butterflys[a].pos+=butterflys[a].rspeed,butterflys[a].deg=0<butterflys[a].rspeed?butterflys[a].pos+rad(90):butterflys[a].pos-rad(90),butterflys[a].x=butterflys[a].cx+butterflys[a].r*cos(butterflys[a].pos),butterflys[a].y=butterflys[a].cy+butterflys[a].r*sin(butterflys[a].pos),dis2(butterflys[a].x,butterflys[a].y,pl.x,pl.y)<judge.butterfly&&kill(),(0<butterflys[a].rspeed&&-50>butterflys[a].y||0>butterflys[a].rspeed&&butterflys[a].y>height+
50)&&butterflys.splice(a,1)}function starMove(){for(var a=stars.length-1;0<=a;a--)stars[a].deg+=stars[a].rspeed,stars[a].x+=starSpeed*cos(stars[a].aim),stars[a].y+=starSpeed*sin(stars[a].aim),dis2(stars[a].x,stars[a].y,pl.x,pl.y)<judge.star&&kill(),-50>stars[a].x&&stars.splice(a,1)}
function diamondMove(){for(var a=diamonds.length-1;0<=a;a--)diamonds[a].y+=diamonds[a].speed,dis2(diamonds[a].x,diamonds[a].y-15,pl.x,pl.y)<judge.diamond?(eatDiamond(diamonds[a].func),diamonds.splice(a,1)):diamonds[a].y>height+50&&diamonds.splice(a,1)}function waveMove(){for(var a=waves.length-1;0<=a;a--)waves[a].x-=waveSpeed,waves[a].r+=waveRSpeed}
function planeMove(){dis2(mx,my,pl.x,pl.y);pl.ax=mx-(pl.x+plSize*cos(pl.arc))-pl.vx/u1;pl.ay=my-(pl.y+plSize*sin(pl.arc))-pl.vy/u1;dis2(pl.vx,pl.vy,0,0);pl.x+=pl.vx/u2;pl.y+=pl.vy/u2;pl.vx+=pl.ax;pl.vy+=pl.ay;pl.arc=atan2(100,-(my-(pl.y+plSize*sin(pl.arc))))-PI/2}
function clockStart(){timer=setInterval(function(){if(!pause){drawBG();drawCursor();waveMove();drawWaves();planeMove();died||drawPlane();ballMove();drawBalls();bigBallMove();drawBigBalls();butterflyMove();drawButterflys();starMove();drawStars();diamondMove();drawDiamonds();!died&&(1==level&&0==clock%25||1<level&&0==clock%20)&&addWave();random()<diamondDensity&&addDiamond();1>level?(1200>clock&&random()<ballDensity*clock/1200||1200<=clock&&random()<ballDensity)&&addBall(rad(ran(175,185))):random()<
ballDensity/2&&addBall(rad(ran(175,185)));(1==level||4==level||5==level||6<level)&&random()<bigBallDensity&&addBigBall(rad(ran(175,185)));(2==level||5==level||6<=level)&&0==clock%100&&addButterfly();(3==level||4==level||6<=level)&&0==clock%starDensity&&addStar();if(!died){cv.save();for(var a=_top_score+(clock+score)+"0  "+_top_life,b=0;b<life;b++)a+="\u2764";a+="  "+_top_level+(6<level?"MAX":level+1);cv.font="20px Arial";b=min(1,dis2(pl.x,pl.y,0,0)/cube(height));cv.fillStyle="rgba(221,51,85,"+b+")";
cv.fillText(a,30,30);cv.restore()}clock++;bgColorTimer++;1800==clock&&level++;1800<clock&&600==clock%1200&&level++;8==flash||7==flash||2==flash||1==flash?(cv.save(),cv.fillStyle="rgba(255,255,255,0.5)",cv.fillRect(0,0,width,height),cv.restore(),flash--):flash&&flash--}},1E3/fps)}document.addEventListener("mousemove",function(a){mx=a.x;my=a.y});
document.addEventListener("click",function(a){"retry"==a.target.id?retry():"startbutton"==a.target.id?($("#startgame").remove(),$(".title").remove(),$("html").css({cursor:"none"}),clockStart(),$("#music")[0].play()):"continue"==a.target.id&&stopPause()});document.addEventListener("keydown",startPause);$("#instructions").mouseenter(function(){$("#instructions").css("background","#1954c0");$("#left").fadeIn(500)});
$("#instructions").mouseleave(function(){$("#instructions").css("background","#3369cd");$("#left").fadeOut(300)});$("#about").mouseenter(function(){$("#about").css("background","#1954c0");$("#right").fadeIn(500)});$("#about").mouseleave(function(){$("#about").css("background","#3369cd");$("#right").fadeOut(300)});function addHelpInfo(){$("#left").append(instructionsContent)}function addAboutInfo(){$("#right").append(aboutContent)}
function addRankingInfo(a){void 0==localStorage.getItem(localStorage.count)&&localStorage.setItem(localStorage.count,a);for(a=1;a<=localStorage.count;a++)scoreArr[a-1]=parseInt(localStorage.getItem(a));var b;for(a=0;a<scoreArr.length;a++){flag=0;for(var c=scoreArr.length;c>a;c--)scoreArr[c]>scoreArr[c-1]&&(b=scoreArr[c],scoreArr[c]=scoreArr[c-1],scoreArr[c-1]=b,flag=1);if(0==flag)break}for(a=0;5>a;a++)void 0==scoreArr[a]&&(scoreArr[a]=0);a='<div class="right2" style = "margin-top:12px">1. '+scoreArr[0]+
'</div><div class="right2">2. '+scoreArr[1]+'</div><div class="right2">3. '+scoreArr[2]+'</div><div class="right2">4. '+scoreArr[3]+'</div><div class="right2">5. '+scoreArr[4]+"</div>";$("#right2")[0].innerHTML=a}
function startPause(a){if(13==a.keyCode||32==a.keyCode||80==a.keyCode)pause?stopPause():$("#die").length?retry():$("#startgame").length?($("#startgame").remove(),$("html").css({cursor:"none"}),clockStart(),$("#left").fadeOut(300),$("#right").fadeOut(300),$(".title").remove()):0>pauseTimes||($("html").css({cursor:"default"}),pause=!0,pauseTimes--,$("body").append('<div class="title">'+_pause+'</div><div id="pause"><div id="instructions">'+_instructions+'</div><div id="about">ABOUT</div><div id="continue" class="button">'+
_continue+"</div></div>"),$("#pause").css("top",height/2-100+"px"),$("#pause").css("left",width/2-200+"px"),$(".title").css("top",height/2-200+"px"),$(".title").css("left",width/2-$(".title").width()/2+"px"),$("#instructions").mouseenter(function(){$("#instructions").css("background","#1954c0");$("#left").fadeIn(500)}),$("#instructions").mouseleave(function(){$("#instructions").css("background","#3369cd");$("#left").fadeOut(300)}),$("#about").mouseenter(function(){$("#about").css("background","#1954c0");
$("#right").fadeIn(500)}),$("#about").mouseleave(function(){$("#about").css("background","#3369cd");$("#right").fadeOut(300)}),$("#music")[0].pause())}function stopPause(){pause=!1;$("html").css({cursor:"none"});$("#pause").remove();$(".title").remove();$("#left").fadeOut(300);$("#right").fadeOut(300);$("#music")[0].play()}
function eatDiamond(a){if(!died)switch($("#diamondsound")[0].play(),a){case 0:a=ranInt(3,6);showInfo("Score +"+a+"000");func_addScore(a);break;case 1:showInfo(_jiansu);func_slow(2);break;case 2:showInfo(_1up);func_oneUp();break;case 3:showInfo(_wudi);func_wudi(6E3);break;case 4:showInfo(_qingping);func_clear();break;case 5:showInfo(_bianxiao),func_small(2)}}
function showInfo(a){info=a;var b=clock;$("body").append('<div id="info'+b+'" class="info">'+a+"</div>");$("#info"+b).css("left",pl.x-100+"px");$("#info"+b).css("top",pl.y-50+"px");$("#info"+b).fadeOut(1500)}function func_addScore(a){score+=100*a}
function func_slow(a){for(var b in balls)balls[b].speed/=a;for(b in bigBalls)bigBalls[b].speed/=a;for(b in butterflys)butterflys[b].rspeed/=a;for(b in stars)stars[b].speed/=a;ballSpeed/=a;bigBallSpeed/=a;butterflySpeed/=a;starSpeed/=a;ballDensity/=a;bigBallDensity/=a;butterflyDensity/=a;starDensity*=a;waveSpeed/=a;slowTimer=setTimeout(function(){ballSpeed*=a;bigBallSpeed*=a;butterflySpeed*=a;starSpeed*=a;ballDensity*=a;bigBallDensity*=a;butterflyDensity*=a;starDensity/=a;waveSpeed*=a},8E3);flash=
8}function func_oneUp(){life++}function func_wudi(a){wudiTimer&&window.clearTimeout(wudiTimer);wudi=!0;wudiTimer=setTimeout(function(){wudi=!1},a)}function func_clear(){balls=[];bigBalls=[];butterflys=[];stars=[];flash=8}
function func_small(a){for(var b in bigBalls)bigBalls[b].size/=a;bigBallSize/=a;bSize/=a;butterflySize/=a;starSize/=a;plSize/=a;for(b in butterflyShape)butterflyShape[b].r/=a;Star_6=[{r:starSize,t:rad(90)},{r:starSize/2*1.5,t:rad(60)},{r:starSize,t:rad(30)},{r:starSize/2*1.5,t:rad(0)},{r:starSize,t:rad(-30)},{r:starSize/2*1.5,t:rad(-60)},{r:starSize,t:rad(-90)},{r:starSize/2*1.5,t:rad(-120)},{r:starSize,t:rad(-150)},{r:starSize/2*1.5,t:rad(-180)},{r:starSize,t:rad(-210)},{r:starSize/2*1.5,t:rad(-240)}];
planeShape=[{r:1*plSize,t:PI+3.14},{r:.716*plSize,t:PI+-2.98},{r:.443*plSize,t:PI+-2.49},{r:.443*plSize,t:PI-.65},{r:.716*plSize,t:PI-.25},{r:1*plSize,t:PI+0},{r:1*plSize,t:PI+0},{r:.716*plSize,t:PI+.25},{r:.443*plSize,t:PI+.65},{r:.443*plSize,t:PI+2.49},{r:.716*plSize,t:PI+2.98}];judge={ball:cube(plSize/4+ballSize),bigBall:cube(plSize/4+bigBallSize),butterfly:cube(plSize/4+butterflySize),star:cube(plSize/4+starSize),diamond:cube(plSize/4+15)};smallTimer=setTimeout(function(){bigBallSize*=a;bSize*=
a;butterflySize*=a;starSize*=a;plSize*=a;for(b in butterflyShape)butterflyShape[b].r*=a;Star_6=[{r:starSize,t:rad(90)},{r:starSize/2*1.5,t:rad(60)},{r:starSize,t:rad(30)},{r:starSize/2*1.5,t:rad(0)},{r:starSize,t:rad(-30)},{r:starSize/2*1.5,t:rad(-60)},{r:starSize,t:rad(-90)},{r:starSize/2*1.5,t:rad(-120)},{r:starSize,t:rad(-150)},{r:starSize/2*1.5,t:rad(-180)},{r:starSize,t:rad(-210)},{r:starSize/2*1.5,t:rad(-240)}];planeShape=[{r:1*plSize,t:PI+3.14},{r:.716*plSize,t:PI+-2.98},{r:.443*plSize,t:PI+
-2.49},{r:.443*plSize,t:PI-.65},{r:.716*plSize,t:PI-.25},{r:1*plSize,t:PI+0},{r:1*plSize,t:PI+0},{r:.716*plSize,t:PI+.25},{r:.443*plSize,t:PI+.65},{r:.443*plSize,t:PI+2.49},{r:.716*plSize,t:PI+2.98}];judge={ball:cube(plSize/4+ballSize),bigBall:cube(plSize/4+bigBallSize),butterfly:cube(plSize/4+butterflySize),star:cube(plSize/4+starSize),diamond:cube(plSize/4+15)}},8E3);flash=8}function kill(){wudi||died||(life--,showInfo(_life+life),func_wudi(2500),$("#killsound")[0].play());life||die()}
function die(){if(!died){died=!0;playNum++;localStorage.count?localStorage.count++:localStorage.count=1;$("html").css({cursor:"default"});var a=clock+score;$("body").append('<div class="title">'+_gameover+'</div><div id="die"><div id="score">'+_scoreis+a+'0</div><div id="ranking">'+_ranking+'</div><div id="retry" class="button">'+_tryagain+"</div></div>");addRankingInfo(a+"0");$("#die").css("top",height/2-100+"px");$("#die").css("left",width/2-200+"px");$(".title").css("top",height/2-200+"px");$(".title").css("left",
width/2-$(".title").width()/2+"px");$("#right2").css("width","150px");$("#right2").css("vertical-align","center");$("#ranking").mouseenter(function(){$("#ranking").css("background","#1954c0");$("#right2").fadeIn(500)});$("#ranking").mouseleave(function(){$("#ranking").css("background","#3369cd");$("#right2").fadeOut(300)});$("#diesound")[0].play()}}
function retry(){$("#die").remove();$(".title").remove();$("html").css({cursor:"none"});$(".info").remove();prepossessing();$("#music")[0].pause();$("#music")[0].currentTime=0;$("#music")[0].play();$("#right2").fadeOut(300)};
